-- MySQL Script generated by MySQL Workbench
-- sön  6 dec 2020 13:39:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ecom1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Ecom1` ;

-- -----------------------------------------------------
-- Schema Ecom1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ecom1` ;
USE `Ecom1` ;

-- -----------------------------------------------------
-- Table `Ecom1`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`User` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecom1`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`Product` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `image_path` VARCHAR(255) NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecom1`.`Basket_Entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`Basket_Entry` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`Basket_Entry` (
  `idBasket_Entry` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idBasket_Entry`, `idProduct`, `idUser`),
  INDEX `fk_Basket_entry_Product1_idx` (`idProduct` ASC) VISIBLE,
  INDEX `fk_Basket_entry_User1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Basket_entry_Product1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `Ecom1`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Basket_entry_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `Ecom1`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecom1`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`Admin` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecom1`.`Sold_Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`Sold_Product` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`Sold_Product` (
  `idSold_Product` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idSold_Product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecom1`.`User_has_Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`User_has_Order` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`User_has_Order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `order_date` DATE NOT NULL,
  PRIMARY KEY (`idOrder`, `idUser`),
  INDEX `fk_User_has_Order_History_User1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Order_History_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `Ecom1`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecom1`.`Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`Review` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`Review` (
  `idComment` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(45) NOT NULL,
  `rating` INT NOT NULL,
  `comment` VARCHAR(255) NOT NULL,
  `idProduct` INT NOT NULL,
  PRIMARY KEY (`idComment`, `idProduct`),
  INDEX `fk_Comment_Product1_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_Product1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `Ecom1`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecom1`.`Order_Entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`Order_Entry` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`Order_Entry` (
  `idOrder` INT NOT NULL,
  `idSold_Product` INT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `fk_Order_Entry_Sold_Product1_idx` (`idSold_Product` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Entry_Sold_Product1`
    FOREIGN KEY (`idSold_Product`)
    REFERENCES `Ecom1`.`Sold_Product` (`idSold_Product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Entry_User_has_Order1`
    FOREIGN KEY (`idOrder`)
    REFERENCES `Ecom1`.`User_has_Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
