-- MySQL Script generated by MySQL Workbench
-- sön  6 dec 2020 13:39:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ecom1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Ecom1` ;

-- -----------------------------------------------------
-- Schema Ecom1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ecom1` ;
USE `Ecom1` ;

-- -----------------------------------------------------
-- Table `Ecom1`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`User` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecom1`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`Product` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `image_path` VARCHAR(255) NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecom1`.`Basket_Entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`Basket_Entry` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`Basket_Entry` (
  `idBasket_Entry` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idBasket_Entry`, `idProduct`, `idUser`),
  INDEX `fk_Basket_entry_Product1_idx` (`idProduct` ASC) VISIBLE,
  INDEX `fk_Basket_entry_User1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Basket_entry_Product1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `Ecom1`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Basket_entry_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `Ecom1`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecom1`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`Admin` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecom1`.`Sold_Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`Sold_Product` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`Sold_Product` (
  `idSold_Product` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idSold_Product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecom1`.`User_has_Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`User_has_Order` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`User_has_Order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `order_date` DATE NOT NULL,
  PRIMARY KEY (`idOrder`, `idUser`),
  INDEX `fk_User_has_Order_History_User1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Order_History_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `Ecom1`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecom1`.`Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`Review` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`Review` (
  `idComment` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(45) NOT NULL,
  `rating` INT NOT NULL,
  `comment` VARCHAR(255) NOT NULL,
  `idProduct` INT NOT NULL,
  PRIMARY KEY (`idComment`, `idProduct`),
  INDEX `fk_Comment_Product1_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_Product1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `Ecom1`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecom1`.`Order_Entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecom1`.`Order_Entry` ;

CREATE TABLE IF NOT EXISTS `Ecom1`.`Order_Entry` (
  `idOrder` INT NOT NULL,
  `idSold_Product` INT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`idOrder`),
<<<<<<< HEAD
  INDEX `fk_Order_Entry_Sold_Product1_idx` (`idSold_Product` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Entry_Sold_Product1`
    FOREIGN KEY (`idSold_Product`)
    REFERENCES `Ecom1`.`Sold_Product` (`idSold_Product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Entry_User_has_Order1`
    FOREIGN KEY (`idOrder`)
    REFERENCES `Ecom1`.`User_has_Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
=======
  KEY `fk_Order_History_Sold_Product1_idx` (`idSold_Product`),
  CONSTRAINT `fk_Order_History_Sold_Product1` FOREIGN KEY (`idSold_Product`) REFERENCES `Sold_Product` (`idSold_Product`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `Order_History`
--

LOCK TABLES `Order_History` WRITE;
/*!40000 ALTER TABLE `Order_History` DISABLE KEYS */;
INSERT INTO `Order_History` VALUES (2,2,5),(3,2,5),(4,1,25);
/*!40000 ALTER TABLE `Order_History` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `Product`
--

DROP TABLE IF EXISTS `Product`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `Product` (
  `idProduct` int NOT NULL AUTO_INCREMENT,
  `name` varchar(45) DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `description` mediumtext,
  `Brand` varchar(45) DEFAULT NULL,
  `picture` BLOB,
  PRIMARY KEY (`idProduct`),
  UNIQUE KEY `name_UNIQUE` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `Product`
--

LOCK TABLES `Product` WRITE;
/*!40000 ALTER TABLE `Product` DISABLE KEYS */;
/*!40000 ALTER TABLE `Product` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `Sold_Product`
--

DROP TABLE IF EXISTS `Sold_Product`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `Sold_Product` (
  `idSold_Product` int NOT NULL AUTO_INCREMENT,
  `name` varchar(45) DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`idSold_Product`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `Sold_Product`
--

LOCK TABLES `Sold_Product` WRITE;
/*!40000 ALTER TABLE `Sold_Product` DISABLE KEYS */;
INSERT INTO `Sold_Product` VALUES (1,'pizza',5.00),(2,'kebab',10.20),(3,'kebab',10.20);
/*!40000 ALTER TABLE `Sold_Product` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `User`
--

DROP TABLE IF EXISTS `User`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `User` (
  `idUser` int NOT NULL AUTO_INCREMENT,
  `username` varchar(45) DEFAULT NULL,
  `password` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idUser`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `User`
--

LOCK TABLES `User` WRITE;
/*!40000 ALTER TABLE `User` DISABLE KEYS */;
INSERT INTO `User` VALUES (1,'filip','pass'),(2,'max','pass'),(3,'wille','pass'),(4,'filip','pass'),(5,'maxskogh','bobpass');
/*!40000 ALTER TABLE `User` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `User_has_Order`
--

DROP TABLE IF EXISTS `User_has_Order`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `User_has_Order` (
  `idUser` int NOT NULL,
  `idOrder` int NOT NULL,
  `order_date` date DEFAULT NULL,
  PRIMARY KEY (`idUser`,`idOrder`),
  UNIQUE KEY `idOrder_UNIQUE` (`idOrder`),
  KEY `fk_User_has_Order_History_Order_History1_idx` (`idOrder`),
  KEY `fk_User_has_Order_History_User1_idx` (`idUser`),
  CONSTRAINT `fk_User_has_Order_History_Order_History1` FOREIGN KEY (`idOrder`) REFERENCES `Order_History` (`idOrder`),
  CONSTRAINT `fk_User_has_Order_History_User1` FOREIGN KEY (`idUser`) REFERENCES `User` (`idUser`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `User_has_Order`
--

LOCK TABLES `User_has_Order` WRITE;
/*!40000 ALTER TABLE `User_has_Order` DISABLE KEYS */;
INSERT INTO `User_has_Order` VALUES (1,2,'2019-12-19'),(1,3,'2020-01-01'),(2,4,'2020-01-01');
/*!40000 ALTER TABLE `User_has_Order` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2020-11-27 13:46:40
>>>>>>> 26094e3f799c33d38fa778472d1df3f4fead54b9
